// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: model/membership_event.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MembershipEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	Node     *Membership            `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *MembershipEvent) Reset() {
	*x = MembershipEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_membership_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembershipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipEvent) ProtoMessage() {}

func (x *MembershipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_model_membership_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipEvent.ProtoReflect.Descriptor instead.
func (*MembershipEvent) Descriptor() ([]byte, []int) {
	return file_model_membership_event_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipEvent) GetLoadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoadedAt
	}
	return nil
}

func (x *MembershipEvent) GetNode() *Membership {
	if x != nil {
		return x.Node
	}
	return nil
}

type Membership struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CancelOn   int32  `protobuf:"varint,1,opt,name=cancelOn,proto3" json:"cancelOn,omitempty"`
	ClientId   string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	EndOn      string `protobuf:"bytes,3,opt,name=endOn,proto3" json:"endOn,omitempty"`
	Id         string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Interval   string `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	LocationId string `protobuf:"bytes,6,opt,name=locationId,proto3" json:"locationId,omitempty"`
	Name       string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	ProductId  string `protobuf:"bytes,8,opt,name=productId,proto3" json:"productId,omitempty"`
	StartOn    int32  `protobuf:"varint,9,opt,name=startOn,proto3" json:"startOn,omitempty"`
	Status     string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	TermNumber string `protobuf:"bytes,11,opt,name=termNumber,proto3" json:"termNumber,omitempty"`
	UnitPrice  int32  `protobuf:"varint,12,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
}

func (x *Membership) Reset() {
	*x = Membership{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_membership_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_model_membership_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_model_membership_event_proto_rawDescGZIP(), []int{1}
}

func (x *Membership) GetCancelOn() int32 {
	if x != nil {
		return x.CancelOn
	}
	return 0
}

func (x *Membership) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Membership) GetEndOn() string {
	if x != nil {
		return x.EndOn
	}
	return ""
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Membership) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Membership) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Membership) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Membership) GetStartOn() int32 {
	if x != nil {
		return x.StartOn
	}
	return 0
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Membership) GetTermNumber() string {
	if x != nil {
		return x.TermNumber
	}
	return ""
}

func (x *Membership) GetUnitPrice() int32 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

var File_model_membership_event_proto protoreflect.FileDescriptor

var file_model_membership_event_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6b, 0x0a, 0x0f, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0xc8, 0x02, 0x0a,
	0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4f,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x72,
	0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x65, 0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x6e, 0x69,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x6e,
	0x69, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x62, 0x6f, 0x75, 0x6c, 0x65,
	0x76, 0x61, 0x72, 0x64, 0x2d, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_membership_event_proto_rawDescOnce sync.Once
	file_model_membership_event_proto_rawDescData = file_model_membership_event_proto_rawDesc
)

func file_model_membership_event_proto_rawDescGZIP() []byte {
	file_model_membership_event_proto_rawDescOnce.Do(func() {
		file_model_membership_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_membership_event_proto_rawDescData)
	})
	return file_model_membership_event_proto_rawDescData
}

var file_model_membership_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_membership_event_proto_goTypes = []interface{}{
	(*MembershipEvent)(nil),       // 0: MembershipEvent
	(*Membership)(nil),            // 1: Membership
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_model_membership_event_proto_depIdxs = []int32{
	2, // 0: MembershipEvent.loaded_at:type_name -> google.protobuf.Timestamp
	1, // 1: MembershipEvent.node:type_name -> Membership
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_membership_event_proto_init() }
func file_model_membership_event_proto_init() {
	if File_model_membership_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_membership_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MembershipEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_membership_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Membership); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_membership_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_membership_event_proto_goTypes,
		DependencyIndexes: file_model_membership_event_proto_depIdxs,
		MessageInfos:      file_model_membership_event_proto_msgTypes,
	}.Build()
	File_model_membership_event_proto = out.File
	file_model_membership_event_proto_rawDesc = nil
	file_model_membership_event_proto_goTypes = nil
	file_model_membership_event_proto_depIdxs = nil
}
